In [37]:
import pandas as pd
url="https://docs.google.com/spreadsheets/d/e/2PACX-1vQcpVvVioO23cndDwr1UmKhndrSq6ES6ZUKZ4fkBBqIAavd1_coVPO_yeOye-Ub-cAWlkX3psJvOU8o/pub?output=csv"
df = pd.read_csv(url)
df.info()
df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

         date   meantemp  humidity  wind_speed  meanpressure
0  2013-01-01  10.000000      84.5    0.000000   1015.666667
1  2013-01-02   7.400000      92.0    2.980000   1017.800000
2  2013-01-03   7.166667      87.0    4.633333   1018.666667

#pd.to_datetime

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيحوّل عمود التاريخ من string لـ datetime وبيحطه في عمود جديد</strong>
</p>

In [38]:

#Add a datetime column based on the string in the "date" column
df['datetime'] = pd.to_datetime(df['date'])
df.info()
df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
 5   datetime      1462 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.7+ KB

         date   meantemp  humidity  wind_speed  meanpressure   datetime
0  2013-01-01  10.000000      84.5    0.000000   1015.666667 2013-01-01
1  2013-01-02   7.400000      92.0    2.980000   1017.800000 2013-01-02
2  2013-01-03   7.166667      87.0    4.633333   1018.666667 2013-01-03

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب القيمة الأولى من عمود date — بترجع كـ string عادي</strong>
</p>

In [39]:
## preview first row from the date column (string)
df.loc[0,'date']

'2013-01-01'

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب القيمة الأولى من عمود datetime — بترجع كـ Timestamp</strong>
</p>

In [40]:
## preview first row from the datetime column (datetime64[ns])
df.loc[0,'datetime']

Timestamp('2013-01-01 00:00:00')

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيحوّل الـ Timestamp لنص بصيغة معينة مثل "January 01, 2013"</strong>
</p>

In [41]:
## demonstrate format code
fmt = "%B %d, %Y"
df.loc[0,'datetime'].strftime(fmt)

'January 01, 2013'

# .dt.strftime

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيطبّق تنسيق معين على كل العمود ويرجعه كـ string</strong>
</p>

In [42]:
df['datetime_fmt'] = df['datetime'].dt.strftime(fmt)
df['datetime_fmt']

0        January 01, 2013
1        January 02, 2013
2        January 03, 2013
3        January 04, 2013
4        January 05, 2013
              ...
1457    December 28, 2016
1458    December 29, 2016
1459    December 30, 2016
1460    December 31, 2016
1461     January 01, 2017
Name: datetime_fmt, Length: 1462, dtype: object

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
 5   datetime      1462 non-null   datetime64[ns]
 6   datetime_fmt  1462 non-null   object
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 80.1+ KB

# .dt.year/month/day/hour/etc

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب السنة من كل قيمة في عمود datetime</strong>
</p>

In [44]:
df['datetime'].dt.year.head()

0    2013
1    2013
2    2013
3    2013
4    2013
Name: datetime, dtype: int32

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب رقم الشهر من كل قيمة</strong>
</p>

In [45]:
df['datetime'].dt.month.head()

0    1
1    1
2    1
3    1
4    1
Name: datetime, dtype: int32

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب رقم الربع السنوي (1 إلى 4) من كل قيمة</strong>
</p>

In [46]:
## fiscal year quarter
df['datetime'].dt.quarter.head()

0    1
1    1
2    1
3    1
4    1
Name: datetime, dtype: int32

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب رقم اليوم في الأسبوع (0 = الاثنين)</strong>
</p>

In [47]:
## day of the week - numeric
df['datetime'].dt.day_of_week.head()

0    1
1    2
2    3
3    4
4    5
Name: datetime, dtype: int32

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب اسم اليوم كنص مثل "Tuesday"</strong>
</p>

In [48]:
## day of the week - String name
df['datetime'].dt.day_name().head()

0      Tuesday
1    Wednesday
2     Thursday
3       Friday
4     Saturday
Name: datetime, dtype: object

# Setting a Datetime Index

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيحوّل عمود datetime ليصير الـ index للـ DataFrame</strong>
</p>

In [49]:
df = df.set_index('datetime')
df

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2013-01-01,2013-01-01,10.000000,84.500000,0.000000,1015.666667,"January 01, 2013"
2013-01-02,2013-01-02,7.400000,92.000000,2.980000,1017.800000,"January 02, 2013"
2013-01-03,2013-01-03,7.166667,87.000000,4.633333,1018.666667,"January 03, 2013"
2013-01-04,2013-01-04,8.666667,71.333333,1.233333,1017.166667,"January 04, 2013"
2013-01-05,2013-01-05,6.000000,86.833333,3.700000,1016.500000,"January 05, 2013"
...,...,...,...,...,...,...
2016-12-28,2016-12-28,17.217391,68.043478,3.547826,1015.565217,"December 28, 2016"
2016-12-29,2016-12-29,15.238095,87.857143,6.000000,1016.904762,"December 29, 2016"
2016-12-30,2016-12-30,14.095238,89.666667,6.266667,1017.904762,"December 30, 2016"
2016-12-31,2016-12-31,15.052632,87.000000,7.325000,1016.100000,"December 31, 2016"
2017-01-01,2017-01-01,10.000000,100.000000,0.000000,1016.000000,"January 01, 2017"

In [50]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10',
               ...
               '2016-12-23', '2016-12-24', '2016-12-25', '2016-12-26',
               '2016-12-27', '2016-12-28', '2016-12-29', '2016-12-30',
               '2016-12-31', '2017-01-01'],
              dtype='datetime64[ns]', name='datetime', length=1462, freq=None)

# Slicing a Time Series with pandas

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب كل صفوف سنة 2013</strong>
</p>

In [51]:
df.loc['2013']

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2013-01-01,2013-01-01,10.000000,84.500000,0.000000,1015.666667,"January 01, 2013"
2013-01-02,2013-01-02,7.400000,92.000000,2.980000,1017.800000,"January 02, 2013"
2013-01-03,2013-01-03,7.166667,87.000000,4.633333,1018.666667,"January 03, 2013"
2013-01-04,2013-01-04,8.666667,71.333333,1.233333,1017.166667,"January 04, 2013"
2013-01-05,2013-01-05,6.000000,86.833333,3.700000,1016.500000,"January 05, 2013"
...,...,...,...,...,...,...
2013-12-27,2013-12-27,11.875000,79.875000,1.162500,1018.625000,"December 27, 2013"
2013-12-28,2013-12-28,10.875000,70.000000,5.325000,1019.250000,"December 28, 2013"
2013-12-29,2013-12-29,10.571429,69.428571,5.325000,1018.500000,"December 29, 2013"
2013-12-30,2013-12-30,12.375000,79.500000,6.475000,1018.125000,"December 30, 2013"
2013-12-31,2013-12-31,14.500000,89.375000,4.862500,1020.500000,"December 31, 2013"

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب كل الصفوف من 2013 حتى نهاية 2014</strong>
</p>

In [52]:
df.loc['2013':'2014']

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2013-01-01,2013-01-01,10.000000,84.500000,0.000000,1015.666667,"January 01, 2013"
2013-01-02,2013-01-02,7.400000,92.000000,2.980000,1017.800000,"January 02, 2013"
2013-01-03,2013-01-03,7.166667,87.000000,4.633333,1018.666667,"January 03, 2013"
2013-01-04,2013-01-04,8.666667,71.333333,1.233333,1017.166667,"January 04, 2013"
2013-01-05,2013-01-05,6.000000,86.833333,3.700000,1016.500000,"January 05, 2013"
...,...,...,...,...,...,...
2014-12-27,2014-12-27,10.375000,69.000000,2.775000,1018.625000,"December 27, 2014"
2014-12-28,2014-12-28,9.000000,86.000000,0.700000,1019.750000,"December 28, 2014"
2014-12-29,2014-12-29,11.125000,72.625000,1.387500,1017.250000,"December 29, 2014"
2014-12-30,2014-12-30,11.625000,70.625000,2.550000,1014.625000,"December 30, 2014"
2014-12-31,2014-12-31,12.375000,67.125000,2.787500,1016.875000,"December 31, 2014"

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب من بداية 2013 حتى يونيو 2014</strong>
</p>

In [53]:
df.loc['2013':'06-2014']

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2013-01-01,2013-01-01,10.000000,84.500000,0.000000,1015.666667,"January 01, 2013"
2013-01-02,2013-01-02,7.400000,92.000000,2.980000,1017.800000,"January 02, 2013"
2013-01-03,2013-01-03,7.166667,87.000000,4.633333,1018.666667,"January 03, 2013"
2013-01-04,2013-01-04,8.666667,71.333333,1.233333,1017.166667,"January 04, 2013"
2013-01-05,2013-01-05,6.000000,86.833333,3.700000,1016.500000,"January 05, 2013"
...,...,...,...,...,...,...
2014-06-26,2014-06-26,32.500000,60.375000,3.237500,1001.000000,"June 26, 2014"
2014-06-27,2014-06-27,34.750000,48.500000,9.487500,1001.625000,"June 27, 2014"
2014-06-28,2014-06-28,34.875000,49.000000,5.787500,999.375000,"June 28, 2014"
2014-06-29,2014-06-29,33.000000,57.750000,9.712500,997.750000,"June 29, 2014"
2014-06-30,2014-06-30,32.000000,67.750000,3.250000,997.500000,"June 30, 2014"

In [54]:
# Just to demonstrate the flexibility, we can use different formats in one line of code
df.loc['March, 2013':'06-2014']

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2013-03-01,2013-03-01,17.333333,49.333333,24.066667,1016.333333,"March 01, 2013"
2013-03-02,2013-03-02,19.000000,54.000000,15.725000,1016.250000,"March 02, 2013"
2013-03-03,2013-03-03,19.333333,62.833333,8.633333,1016.166667,"March 03, 2013"
2013-03-04,2013-03-04,17.600000,71.000000,5.560000,1015.800000,"March 04, 2013"
2013-03-05,2013-03-05,20.875000,61.875000,4.162500,1016.375000,"March 05, 2013"
...,...,...,...,...,...,...
2014-06-26,2014-06-26,32.500000,60.375000,3.237500,1001.000000,"June 26, 2014"
2014-06-27,2014-06-27,34.750000,48.500000,9.487500,1001.625000,"June 27, 2014"
2014-06-28,2014-06-28,34.875000,49.000000,5.787500,999.375000,"June 28, 2014"
2014-06-29,2014-06-29,33.000000,57.750000,9.712500,997.750000,"June 29, 2014"
2014-06-30,2014-06-30,32.000000,67.750000,3.250000,997.500000,"June 30, 2014"

#**Finding dates of extreme values - using .idxmax() and .idxmin()**

# Option 1: Find max and filter (not recommended)

In [55]:
## using max and slicing to find the index
max_humid = df['humidity'].max()
most_humid_date = df.loc[ df['humidity']==max_humid]
max_date = most_humid_date.index
most_humid_date

,date,meantemp,humidity,wind_speed,meanpressure,datetime_fmt
datetime,,,,,,
2017-01-01,2017-01-01,10.0,100.0,0.0,1016.0,"January 01, 2017"

In [56]:
## now print the requested statement
print(f"The most humid day was {max_date.strftime('%m/%d/%Y')}, which was a {max_date.day_name()}.")


print(f" The humidity was {max_humid}, and the average temperature was {most_humid_date['meantemp']}")

The most humid day was Index(['01/01/2017'], dtype='object', name='datetime'), which was a Index(['Sunday'], dtype='object', name='datetime').
 The humidity was 100.0, and the average temperature was datetime
2017-01-01    10.0
Name: meantemp, dtype: float64

# Option 2: Using .idxmax() (recommended)

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيرجع الـ Timestamp (التاريخ) اللي فيه أعلى قيمة humidity</strong>
</p>

In [57]:
max_date = df['humidity'].idxmax()
max_date

Timestamp('2017-01-01 00:00:00')

In [58]:
df.loc[max_date]

date                  2017-01-01
meantemp                    10.0
humidity                   100.0
wind_speed                   0.0
meanpressure              1016.0
datetime_fmt    January 01, 2017
Name: 2017-01-01 00:00:00, dtype: object

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيجيب الصف كامل اللي تاريخه = max_date</strong>
</p>

In [59]:
## TEDIOUS WAY/BAD WAY
## Saving each value from the series as separate variables
str_date = df.loc[max_date,'date']
temp = df.loc[max_date,'meantemp']
humidity = df.loc[max_date,'humidity']
wind = df.loc[max_date,'wind_speed']
pressure = df.loc[max_date,'meanpressure']
# Proving that it worked!
str_date, temp, humidity, wind, pressure

('2017-01-01',
 np.float64(10.0),
 np.float64(100.0),
 np.float64(0.0),
 np.float64(1016.0))

In [60]:
df.loc[max_date]

date                  2017-01-01
meantemp                    10.0
humidity                   100.0
wind_speed                   0.0
meanpressure              1016.0
datetime_fmt    January 01, 2017
Name: 2017-01-01 00:00:00, dtype: object

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيفك قيم الصف الواحد وبيحطها في متغيرات منفصلة دفعة واحدة — هاد اسمه tuple unpacking</strong>
</p>

In [61]:
## Saving each value from the series as separate variables
str_date, temp, humidity, wind, pressure = df.loc[max_date][['date', 'meantemp', 'humidity', 'wind_speed', 'meanpressure']]
# Proving that it worked!
str_date, temp, humidity, wind, pressure

('2017-01-01',
 np.float64(10.0),
 np.float64(100.0),
 np.float64(0.0),
 np.float64(1016.0))

<p dir="rtl" style="font-size: 24px; color: #000000; font-weight: 900;">
  <strong>بيحوّل الـ Timestamp لنص بصيغة mm/dd/yyyy</strong>
</p>

In [62]:
## now print the requested statement
print(f"The most humid day was {max_date.strftime('%m/%d/%Y')}, which was a {max_date.day_name()}.")
print(f"The humidity was {humidity:.2f}, and the average temperature was {temp:.2f}.")

The most humid day was 01/01/2017, which was a Sunday.
The humidity was 100.00, and the average temperature was 10.00.